//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eskuvo_tervezo.Properties.ResourceEng", typeof(ResourceEng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string BT_Back {
            get {
                return ResourceManager.GetString("BT_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse picture.
        /// </summary>
        public static string BT_BrowsePicture {
            get {
                return ResourceManager.GetString("BT_BrowsePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BT_Cancel {
            get {
                return ResourceManager.GetString("BT_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BT_Delete {
            get {
                return ResourceManager.GetString("BT_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download pictures.
        /// </summary>
        public static string BT_DownloadPicture {
            get {
                return ResourceManager.GetString("BT_DownloadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string BT_Exit {
            get {
                return ResourceManager.GetString("BT_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel file.
        /// </summary>
        public static string BT_ExportToExcel {
            get {
                return ResourceManager.GetString("BT_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BT_Login {
            get {
                return ResourceManager.GetString("BT_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string BT_Modification {
            get {
                return ResourceManager.GetString("BT_Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BT_No {
            get {
                return ResourceManager.GetString("BT_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string BT_Reg {
            get {
                return ResourceManager.GetString("BT_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BT_Save {
            get {
                return ResourceManager.GetString("BT_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BT_SaveBride {
            get {
                return ResourceManager.GetString("BT_SaveBride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BT_SaveGroom {
            get {
                return ResourceManager.GetString("BT_SaveGroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BT_SavePics {
            get {
                return ResourceManager.GetString("BT_SavePics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BT_SaveRadioChannel {
            get {
                return ResourceManager.GetString("BT_SaveRadioChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BT_Search {
            get {
                return ResourceManager.GetString("BT_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BT_Yes {
            get {
                return ResourceManager.GetString("BT_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string CB_Lan {
            get {
                return ResourceManager.GetString("CB_Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Wedding.
        /// </summary>
        public static string DateOfWedding {
            get {
                return ResourceManager.GetString("DateOfWedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string Dialog_ImageFiles {
            get {
                return ResourceManager.GetString("Dialog_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitWarning {
            get {
                return ResourceManager.GetString("ExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string LB_Address {
            get {
                return ResourceManager.GetString("LB_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LB_Amount {
            get {
                return ResourceManager.GetString("LB_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LB_Back {
            get {
                return ResourceManager.GetString("LB_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bride.
        /// </summary>
        public static string LB_Bride {
            get {
                return ResourceManager.GetString("LB_Bride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string LB_BrideCount {
            get {
                return ResourceManager.GetString("LB_BrideCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts of guests.
        /// </summary>
        public static string LB_BrideGuestCount {
            get {
                return ResourceManager.GetString("LB_BrideGuestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, family.
        /// </summary>
        public static string LB_BrideName {
            get {
                return ResourceManager.GetString("LB_BrideName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string LB_Budget {
            get {
                return ResourceManager.GetString("LB_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparsion.
        /// </summary>
        public static string LB_Comparsion {
            get {
                return ResourceManager.GetString("LB_Comparsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string LB_Contact {
            get {
                return ResourceManager.GetString("LB_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string LB_Cost {
            get {
                return ResourceManager.GetString("LB_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string LB_Count {
            get {
                return ResourceManager.GetString("LB_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string LB_Diary {
            get {
                return ResourceManager.GetString("LB_Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string LB_Email {
            get {
                return ResourceManager.GetString("LB_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending interval.
        /// </summary>
        public static string LB_EndingInterval {
            get {
                return ResourceManager.GetString("LB_EndingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entry.
        /// </summary>
        public static string LB_Entry {
            get {
                return ResourceManager.GetString("LB_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string LB_Expense {
            get {
                return ResourceManager.GetString("LB_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string LB_Expenses {
            get {
                return ResourceManager.GetString("LB_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LB_FirstAmount {
            get {
                return ResourceManager.GetString("LB_FirstAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First offer.
        /// </summary>
        public static string LB_FirstOffer {
            get {
                return ResourceManager.GetString("LB_FirstOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First steps.
        /// </summary>
        public static string LB_FirstSteps {
            get {
                return ResourceManager.GetString("LB_FirstSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom.
        /// </summary>
        public static string LB_Groom {
            get {
                return ResourceManager.GetString("LB_Groom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string LB_GroomCount {
            get {
                return ResourceManager.GetString("LB_GroomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts of guests.
        /// </summary>
        public static string LB_GroomGuestCount {
            get {
                return ResourceManager.GetString("LB_GroomGuestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, family.
        /// </summary>
        public static string LB_GroomName {
            get {
                return ResourceManager.GetString("LB_GroomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string LB_Guests {
            get {
                return ResourceManager.GetString("LB_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string LB_Modify {
            get {
                return ResourceManager.GetString("LB_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LB_Name {
            get {
                return ResourceManager.GetString("LB_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string LB_NewPassword {
            get {
                return ResourceManager.GetString("LB_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password again.
        /// </summary>
        public static string LB_NewPasswordAgain {
            get {
                return ResourceManager.GetString("LB_NewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string LB_Offer {
            get {
                return ResourceManager.GetString("LB_Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string LB_OldPassword {
            get {
                return ResourceManager.GetString("LB_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LB_Passwd {
            get {
                return ResourceManager.GetString("LB_Passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password again.
        /// </summary>
        public static string LB_PasswdAgain {
            get {
                return ResourceManager.GetString("LB_PasswdAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string LB_Phone {
            get {
                return ResourceManager.GetString("LB_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string LB_Quote {
            get {
                return ResourceManager.GetString("LB_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string LB_Radio {
            get {
                return ResourceManager.GetString("LB_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio channel&apos;s name.
        /// </summary>
        public static string LB_RadioChannelName {
            get {
                return ResourceManager.GetString("LB_RadioChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio list.
        /// </summary>
        public static string LB_RadioList {
            get {
                return ResourceManager.GetString("LB_RadioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining days:.
        /// </summary>
        public static string LB_RemainingDays {
            get {
                return ResourceManager.GetString("LB_RemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LB_SecondAmount {
            get {
                return ResourceManager.GetString("LB_SecondAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second offer.
        /// </summary>
        public static string LB_SecondOffer {
            get {
                return ResourceManager.GetString("LB_SecondOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LB_Settings {
            get {
                return ResourceManager.GetString("LB_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting interval.
        /// </summary>
        public static string LB_StartingInterval {
            get {
                return ResourceManager.GetString("LB_StartingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream link.
        /// </summary>
        public static string LB_StreamLink {
            get {
                return ResourceManager.GetString("LB_StreamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Planner.
        /// </summary>
        public static string LB_Title {
            get {
                return ResourceManager.GetString("LB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string LB_Title_reg {
            get {
                return ResourceManager.GetString("LB_Title_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LB_TitleHome {
            get {
                return ResourceManager.GetString("LB_TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string LB_Today {
            get {
                return ResourceManager.GetString("LB_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LB_User {
            get {
                return ResourceManager.GetString("LB_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding venue.
        /// </summary>
        public static string LB_Venue {
            get {
                return ResourceManager.GetString("LB_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding venue name.
        /// </summary>
        public static string LB_VenueName {
            get {
                return ResourceManager.GetString("LB_VenueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding venues.
        /// </summary>
        public static string LB_Venues {
            get {
                return ResourceManager.GetString("LB_Venues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        public static string LB_Volume {
            get {
                return ResourceManager.GetString("LB_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding day.
        /// </summary>
        public static string LB_WeddingDay {
            get {
                return ResourceManager.GetString("LB_WeddingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LB_Welcome {
            get {
                return ResourceManager.GetString("LB_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advices.
        /// </summary>
        public static string Menu_Advices {
            get {
                return ResourceManager.GetString("Menu_Advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceremony.
        /// </summary>
        public static string Menu_Ceremony {
            get {
                return ResourceManager.GetString("Menu_Ceremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparsion.
        /// </summary>
        public static string Menu_Comparsion {
            get {
                return ResourceManager.GetString("Menu_Comparsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetics.
        /// </summary>
        public static string Menu_Cosmetic {
            get {
                return ResourceManager.GetString("Menu_Cosmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary Date.
        /// </summary>
        public static string Menu_DiaryDate {
            get {
                return ResourceManager.GetString("Menu_DiaryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dress.
        /// </summary>
        public static string Menu_Dress {
            get {
                return ResourceManager.GetString("Menu_Dress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Menu_Expenses {
            get {
                return ResourceManager.GetString("Menu_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string Menu_ExpensesAdvance {
            get {
                return ResourceManager.GetString("Menu_ExpensesAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned expenses.
        /// </summary>
        public static string Menu_ExpensesPlanned {
            get {
                return ResourceManager.GetString("Menu_ExpensesPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First steps.
        /// </summary>
        public static string Menu_FirstSteps {
            get {
                return ResourceManager.GetString("Menu_FirstSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowers.
        /// </summary>
        public static string Menu_Flowers {
            get {
                return ResourceManager.GetString("Menu_Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Menu_Freight {
            get {
                return ResourceManager.GetString("Menu_Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string Menu_Guests {
            get {
                return ResourceManager.GetString("Menu_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest welcome.
        /// </summary>
        public static string Menu_GuestWelcome {
            get {
                return ResourceManager.GetString("Menu_GuestWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeymoon.
        /// </summary>
        public static string Menu_Honeymoon {
            get {
                return ResourceManager.GetString("Menu_Honeymoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        public static string Menu_Photographer {
            get {
                return ResourceManager.GetString("Menu_Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string Menu_Planning {
            get {
                return ResourceManager.GetString("Menu_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string Menu_Radio {
            get {
                return ResourceManager.GetString("Menu_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venues.
        /// </summary>
        public static string Menu_Venue {
            get {
                return ResourceManager.GetString("Menu_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this log entry?.
        /// </summary>
        public static string Message_Delete {
            get {
                return ResourceManager.GetString("Message_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Message_Delete_Title {
            get {
                return ResourceManager.GetString("Message_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contact?.
        /// </summary>
        public static string Message_DeleteContact {
            get {
                return ResourceManager.GetString("Message_DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this expense?.
        /// </summary>
        public static string Message_DeleteExp {
            get {
                return ResourceManager.GetString("Message_DeleteExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this wedding venue including these expenses?.
        /// </summary>
        public static string Message_DeleteExpense {
            get {
                return ResourceManager.GetString("Message_DeleteExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this guest?.
        /// </summary>
        public static string Message_DeleteGuest {
            get {
                return ResourceManager.GetString("Message_DeleteGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this picture?.
        /// </summary>
        public static string Message_DeletePics {
            get {
                return ResourceManager.GetString("Message_DeletePics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want delete this channel?.
        /// </summary>
        public static string Message_DeleteRadioChannel {
            get {
                return ResourceManager.GetString("Message_DeleteRadioChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this wedding venue including these pictures?.
        /// </summary>
        public static string Message_DeleteVenue {
            get {
                return ResourceManager.GetString("Message_DeleteVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is opened!.
        /// </summary>
        public static string Message_FileIsOpenText {
            get {
                return ResourceManager.GetString("Message_FileIsOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully save!.
        /// </summary>
        public static string Message_FileIsOpenTitle {
            get {
                return ResourceManager.GetString("Message_FileIsOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet connection is disconnected, the internet radio will be unavailable!.
        /// </summary>
        public static string Message_InternetConnection {
            get {
                return ResourceManager.GetString("Message_InternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection.
        /// </summary>
        public static string Message_InternetConnectionTitle {
            get {
                return ResourceManager.GetString("Message_InternetConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want logout?.
        /// </summary>
        public static string Message_LogoutText {
            get {
                return ResourceManager.GetString("Message_LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Message_LogoutTitle {
            get {
                return ResourceManager.GetString("Message_LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is reserved!.
        /// </summary>
        public static string Message_Reg {
            get {
                return ResourceManager.GetString("Message_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want a new password? We will send your new password to your specified email address..
        /// </summary>
        public static string Message_RenewPassword {
            get {
                return ResourceManager.GetString("Message_RenewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Message_RenewPasswordTitle {
            get {
                return ResourceManager.GetString("Message_RenewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved!.
        /// </summary>
        public static string MessageBoxSaveText {
            get {
                return ResourceManager.GetString("MessageBoxSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MessageBoxSaveTitle {
            get {
                return ResourceManager.GetString("MessageBoxSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual dates.
        /// </summary>
        public static string RB_Actual {
            get {
                return ResourceManager.GetString("RB_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates.
        /// </summary>
        public static string RB_All {
            get {
                return ResourceManager.GetString("RB_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date interval.
        /// </summary>
        public static string RB_Interval {
            get {
                return ResourceManager.GetString("RB_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx.
        /// </summary>
        public static string SaveFileDialogFilter {
            get {
                return ResourceManager.GetString("SaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel file to.
        /// </summary>
        public static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear .
        /// </summary>
        public static string Send_EmailBody1 {
            get {
                return ResourceManager.GetString("Send_EmailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can access to your account with this password, please change it later..
        /// </summary>
        public static string Send_EmailBody2 {
            get {
                return ResourceManager.GetString("Send_EmailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Regards:
        ///Weddig Planner.
        /// </summary>
        public static string Send_EmailBody3 {
            get {
                return ResourceManager.GetString("Send_EmailBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infogwedding@gmail.com.
        /// </summary>
        public static string Send_EmailFrom {
            get {
                return ResourceManager.GetString("Send_EmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeddingPlanner01.
        /// </summary>
        public static string Send_EmailFromPassword {
            get {
                return ResourceManager.GetString("Send_EmailFromPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string Send_EmailHost {
            get {
                return ResourceManager.GetString("Send_EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeddingPlanner account password changing.
        /// </summary>
        public static string Send_EmailSubject {
            get {
                return ResourceManager.GetString("Send_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your log is sucessfull.
        /// </summary>
        public static string SuccessfulLog {
            get {
                return ResourceManager.GetString("SuccessfulLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 6 characters.
        /// </summary>
        public static string T_Passwd_Tooltip {
            get {
                return ResourceManager.GetString("T_Passwd_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 4 characters.
        /// </summary>
        public static string Tb_Reg_Tooltip {
            get {
                return ResourceManager.GetString("Tb_Reg_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect!.
        /// </summary>
        public static string Tbl_Error {
            get {
                return ResourceManager.GetString("Tbl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Tbl_Reg {
            get {
                return ResourceManager.GetString("Tbl_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Tbl_RePassword {
            get {
                return ResourceManager.GetString("Tbl_RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Title_Reg {
            get {
                return ResourceManager.GetString("Title_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Tooltip_Delete {
            get {
                return ResourceManager.GetString("Tooltip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Tooltip_Download {
            get {
                return ResourceManager.GetString("Tooltip_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous channel.
        /// </summary>
        public static string Tooltip_IconRadioChannelLeft {
            get {
                return ResourceManager.GetString("Tooltip_IconRadioChannelLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next channel.
        /// </summary>
        public static string Tooltip_IconRadioChannelRight {
            get {
                return ResourceManager.GetString("Tooltip_IconRadioChannelRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string Tooltip_ImageReset {
            get {
                return ResourceManager.GetString("Tooltip_ImageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format.
        /// </summary>
        public static string Tooltip_InvalidDateTimeCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidDateTimeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xyxy@xyxy.hu.
        /// </summary>
        public static string Tooltip_InvalidEmailCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidEmailCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least three character.
        /// </summary>
        public static string Tooltip_InvalidNameCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidNameCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least two characters, do not include ( ) &quot; / &apos; &lt; &gt; : ; signs.
        /// </summary>
        public static string Tooltip_InvalidNormalTextCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidNormalTextCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers are allowed.
        /// </summary>
        public static string Tooltip_InvalidNumberCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidNumberCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not your old password.
        /// </summary>
        public static string Tooltip_InvalidOldPassword {
            get {
                return ResourceManager.GetString("Tooltip_InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least eight characters, at least one letter and one number.
        /// </summary>
        public static string Tooltip_InvalidPasswordCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidPasswordCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +36 22 333 4444 , 22 333 4444 , +36-22-333-444.
        /// </summary>
        public static string Tooltip_InvalidPhoneCharacters {
            get {
                return ResourceManager.GetString("Tooltip_InvalidPhoneCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string Tooltip_Modification {
            get {
                return ResourceManager.GetString("Tooltip_Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords are not equals.
        /// </summary>
        public static string Tooltip_PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("Tooltip_PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
