//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarLogEntrys
    {
        public int ID { get; set; }
        public int CalID { get; set; }
        public string LogEntry { get; set; }
    
        public virtual Calendar Calendar { get; set; }
    }
}
