//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public Calendar()
        {
            this.CalendarLogEntrys = new HashSet<CalendarLogEntrys>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<CalendarLogEntrys> CalendarLogEntrys { get; set; }
    }
}
