//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public int Guest_ID { get; set; }
        public int Wedding_ID { get; set; }
        public string Guest_Name { get; set; }
        public int Guest_Count { get; set; }
        public int Bride_Groom { get; set; }
    
        public virtual WeddingData WeddingData { get; set; }
    }
}
