//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int IDLog { get; set; }
        public int UserID { get; set; }
        public string WindowsUser { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string IP_Address { get; set; }
        public string Mac_Address { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
