//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Calendar = new HashSet<Calendar>();
            this.Contacts = new HashSet<Contacts>();
            this.Log = new HashSet<Log>();
            this.Radio = new HashSet<Radio>();
            this.WeddingData = new HashSet<WeddingData>();
        }
    
        public int IDLogin { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<Calendar> Calendar { get; set; }
        public virtual ICollection<Contacts> Contacts { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<Radio> Radio { get; set; }
        public virtual ICollection<WeddingData> WeddingData { get; set; }
    }
}
