//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radio
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string StreamLink { get; set; }
        public string ChannelName { get; set; }
        public Nullable<bool> Chosen { get; set; }
        public Nullable<int> Volume { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
