//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingData
    {
        public WeddingData()
        {
            this.Guests = new HashSet<Guests>();
            this.WeddingVenue = new HashSet<WeddingVenue>();
        }
    
        public int ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Wedding_Date { get; set; }
        public string BrideName { get; set; }
        public string GroomName { get; set; }
        public Nullable<int> Budget { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Guests> Guests { get; set; }
        public virtual Login Login { get; set; }
        public virtual ICollection<WeddingVenue> WeddingVenue { get; set; }
    }
}
