//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeddingPlannerEntities : DbContext
    {
        public WeddingPlannerEntities()
            : base("name=WeddingPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calendar> Calendar { get; set; }
        public DbSet<CalendarLogEntrys> CalendarLogEntrys { get; set; }
        public DbSet<Contacts> Contacts { get; set; }
        public DbSet<Guests> Guests { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Login> Login { get; set; }
        public DbSet<Radio> Radio { get; set; }
        public DbSet<WeddingData> WeddingData { get; set; }
        public DbSet<WeddingExpenses> WeddingExpenses { get; set; }
        public DbSet<WeddingVenue> WeddingVenue { get; set; }
        public DbSet<WeddingVenueImages> WeddingVenueImages { get; set; }
    }
}
