//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eskuvo_tervezo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingVenue
    {
        public WeddingVenue()
        {
            this.WeddingExpenses = new HashSet<WeddingExpenses>();
            this.WeddingVenueImages = new HashSet<WeddingVenueImages>();
        }
    
        public int ID { get; set; }
        public int WeddingID { get; set; }
        public string Wedding_Venue { get; set; }
        public string Venue_Address { get; set; }
    
        public virtual WeddingData WeddingData { get; set; }
        public virtual ICollection<WeddingExpenses> WeddingExpenses { get; set; }
        public virtual ICollection<WeddingVenueImages> WeddingVenueImages { get; set; }
    }
}
